#! /bin/bash 
###########################################
#
###########################################

# constants
baseDir=$(cd `dirname "$0"`;pwd)

# functions

# main 
[ -z "${BASH_SOURCE[0]}" -o "${BASH_SOURCE[0]}" = "$0" ] || return
cd $baseDir/..
export PATH=node_modules/@chatopera/sdk/bin:$PATH

if [ ! -d node_modules/@chatopera/sdk/bin ]; then
    echo "Run admin/install.sh first."
    exit 1
fi

node_modules/@chatopera/sdk/bin/bot.js $*
