+ __kickoff_close_interview
- {@__close_interview}

+ (*)
% {@__close_interview}
- ^sendInterviewReport(<cap1>) {@__say_goodbye}

// 固定话术
+ __close_interview
- 本次面试完成了，您的手机号是什么，以便进一步联系您。
- 面试完成，请发送您的手机号码，以便进后续联系。
- 面试完成，请给我您的手机号码，方便我们后续和您联系。

+ __say_goodbye
- {CLEAR} 感谢您参与本次面试，我们会根据您的能力和该职位进行详细的研究，祝您生活愉快，再会！
- {CLEAR} 感谢能和您进行这样的对话，我们将根据您的才华与该职位的匹配程度进行考虑，祝您生活愉快，再会!
- {CLEAR} 本次面试结束，我们将根据您的才华与该职位的匹配程度进行考虑，祝您生活愉快，再会!