+ 你好
- ^get_greetings()

// FAQ Hotlist
+ __faq_hot_list
- ^get_greetings()

// 获取工作机会列表
+ __faq_job_opennings
- ^get_job_opennings()

+ __faq_describe_nlp
- ^describe_nlp_job()

+ __faq_describe_nodejs
- ^describe_nodejs_job()

+ __prepare_nlp_job_interview
- ^prepare_interview('自然语言处理')

+ __prepare_nodejs_job_interview
- ^prepare_interview('NodeJS')

// 开始面试
+ __start_job_interview
- ^startBasicSection()
